server:
  port: 8200

spring:
  application:
    name: wikimedia.consumer

local:
  kafka-topic-name: wikimedia-logs
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    retry-attempts: 3
    retry-interval: 1000
    retry-backoff-multiplier: 2
    retry-backoff-max-interval: 60000
    dlq-prefix: ""
    dlq-suffix: "-DLQ"
    consumer:
      group.id: wikimedia-elastic-shipper
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto.offset.reset: earliest